<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Description>MES 连接库 - 数据库直连（ADO.NET，支持 SQLite 与 SQL Server）协议 Provider。</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mes.Core\Mes.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

</Project>
